name: Fast API docker build push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos a ejecutar
    # En las pruebas
    - uses: actions/checkout@v3

    - name: Check tests status
      run: python app/test_utils.py

    - name: Build the FastAPI Docker image
      run: docker build -t '${{secrets.DOCKER_LOGIN}}'/fastapi-docker-workflow:'${{github.sha}}' .
      
    - name: Login to docker
      run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.DOCKER_LOGIN}}'/fastapi-docker-workflow:'${{github.sha}}'
  nothing:
    runs-on: ubuntu-latest
    steps:
    - name: just do nothing bro!
      run: echo "i'm doing nothing!" > nothing_to_read.txt
  send_mail:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with: 
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Server port, default 25:
        server_port: 587
        # Required mail subject:
        subject: Github Actions result - success
        # Required recipients' addresses:
        to: david.alberto.guzman@correounivalle.edu.co,mauricio.carrillo@correounivalle.edu.co,alejandro.montero@correounivalle.edu.co,juan.ordonez.hurtado@correounivalle.edu.co
        # Required sender full name (address can be skipped):
        from: Luke Skylwalker # <user@example.com>
        # Optional plain body:
        body: Congratulations!, your repository is now at our production site!.
        # Optional carbon copy recipients:
        # cc: kyloren@example.com,leia@example.com
        # Optional recipient of the email response:
        # reply_to: luke@example.com
        # Optional Message ID this message is replying to:
        # in_reply_to: <random-luke@example.com>
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: high